POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
  "name": "ilker",
  "password": "ilkerkaan",
  "email": "ilker@this.com"
}

###

POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
  "email": "ilker@this.com",
  "password": "ilkerkaan"
}

###

PUT http://localhost:4000/api/v1/auth/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjFjNGY4MTcyNGQ2ZGRmYjM5NGUxNTgiLCJpYXQiOjE2NDYwMjMwOTMsImV4cCI6MTY0NjEwOTQ5M30.xWpH2LvDYeNCyawiamf1Ijypmcpn6PUbuzYNZnkhn7g

{
  "name": "ilkerkaan",
  "lastName": "adgzl",
  "location": "updated location.",
  "email": "ilker@this.com"
}